/*
 * Ce programme permet d'importer un fil de nouvelles pour ensuite consulter ses nouvelles.
 * Il permet égallement d'exporter le fil de nouvelles dans un fichier XML et 
 * de créer, supprimer ou modifier ses nouvelles.
 */
package rss_projet4;

import java.awt.Dimension;
import javax.swing.ImageIcon;

/**
 * Classe pour afficher les notifications
 * @author Sylvain
 */
public class Event_notificationJDialog extends javax.swing.JDialog{
    
    /**
     * Constructeur de la vue de notifications
     */
    public Event_notificationJDialog() {
        initComponents();            
    }
    
    /**
     * Applique le texte à afficher avec l'icône
     * @param notification le texte de notification
     * @param positiveResult le genre de message à afficher (true = confirmer | false = suppression)
     */
    public void setNotification(String notification, boolean positiveResult){
        ImageIcon good = new ImageIcon("./src/images/check.png"); 
        ImageIcon bad = new ImageIcon("./src/images/fault.png");                 
        if(positiveResult)
            jLabel_events_title.setIcon(good);
        else
            jLabel_events_title.setIcon(bad);
        jLabel_events_title.setText(notification);
    }
    
    /**
     * Ajuste le cadre de la vue par rapport au message
     * @param titleWidth la largeur du message
     */
    protected void resizeFrame(int titleWidth){
        if(titleWidth > 30){
            this.setPreferredSize(new Dimension(425 + (titleWidth * 4), 190));
            this.pack();
        }
        this.setLocationRelativeTo(null); 
        this.setVisible(true);
    }     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_bottom = new javax.swing.JPanel();
        jPanel_bottom_event = new javax.swing.JPanel();
        jLabel_events_title = new javax.swing.JLabel();
        jPanel_bottom_toolbar = new javax.swing.JPanel();
        jButton_continuer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);

        jPanel_bottom.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_bottom.setPreferredSize(new java.awt.Dimension(800, 435));

        jPanel_bottom_event.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_bottom_event.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 51), 2));

        jLabel_events_title.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel_events_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_events_title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check.png"))); // NOI18N
        jLabel_events_title.setLabelFor(jLabel_events_title);
        jLabel_events_title.setIconTextGap(20);

        javax.swing.GroupLayout jPanel_bottom_eventLayout = new javax.swing.GroupLayout(jPanel_bottom_event);
        jPanel_bottom_event.setLayout(jPanel_bottom_eventLayout);
        jPanel_bottom_eventLayout.setHorizontalGroup(
            jPanel_bottom_eventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_bottom_eventLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel_events_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        jPanel_bottom_eventLayout.setVerticalGroup(
            jPanel_bottom_eventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_bottom_eventLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel_events_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel_bottomLayout = new javax.swing.GroupLayout(jPanel_bottom);
        jPanel_bottom.setLayout(jPanel_bottomLayout);
        jPanel_bottomLayout.setHorizontalGroup(
            jPanel_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_bottomLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel_bottom_event, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        jPanel_bottomLayout.setVerticalGroup(
            jPanel_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_bottomLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel_bottom_event, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        jPanel_bottom_toolbar.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_bottom_toolbar.setPreferredSize(new java.awt.Dimension(800, 60));
        jPanel_bottom_toolbar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        jButton_continuer.setText("Ok");
        jButton_continuer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_continuer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_continuerActionPerformed(evt);
            }
        });
        jPanel_bottom_toolbar.add(jButton_continuer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_bottom_toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
            .addComponent(jPanel_bottom, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_bottom, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel_bottom_toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Bouton OK (pour fermer la fenêtre)
     * @param evt l'action produite
     */
    private void jButton_continuerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_continuerActionPerformed
        this.dispose(); 
    }//GEN-LAST:event_jButton_continuerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_continuer;
    private javax.swing.JLabel jLabel_events_title;
    private javax.swing.JPanel jPanel_bottom;
    private javax.swing.JPanel jPanel_bottom_event;
    private javax.swing.JPanel jPanel_bottom_toolbar;
    // End of variables declaration//GEN-END:variables

}
