/*
 * Ce programme permet d'importer un fil de nouvelles pour ensuite consulter ses nouvelles.
 * Il permet égallement d'exporter le fil de nouvelles dans un fichier XML et 
 * de créer, supprimer ou modifier ses nouvelles.
 */
package rss_projet4;

import java.io.File;
import javax.swing.UIManager;

/**
 * Classe pour exporter le fil de nouvelles dans un fichier XML
 * @author Sylvain
 */
public class Feeds_exportJDialog extends javax.swing.JDialog {
    
    private final Controller eventsList; //accède au contrôleur
    private final File fileName; //le nom du fichier à exporter
           
    /**
     * Constructeur pour la vue d'exportation
     * @param eventsList le fil de nouvelles
     * @param feedTitle le titre du fil de nouvelles
     */
    public Feeds_exportJDialog(Controller eventsList, String feedTitle) {
        this.eventsList = eventsList;
        this.fileName = new File(feedTitle + ".xml");
        
        //change le texte du bouton
        UIManager.put("FileChooser.cancelButtonText", "Annuler"); //change le texte du bouton
                        
        initComponents();   
        
        //Applique le nom du fichier par défault
        jFileChooser_export.setSelectedFile(fileName); 
        
    }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_header = new javax.swing.JPanel();
        jLabel_header_title = new javax.swing.JLabel();
        jPanel_header_toolbar = new javax.swing.JPanel();
        jPanel_bottom = new javax.swing.JPanel();
        jPanel_export = new javax.swing.JPanel();
        jFileChooser_export = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel_header.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_header_title.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        jLabel_header_title.setForeground(new java.awt.Color(0, 153, 204));
        jLabel_header_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_header_title.setText("Exporter le fil de nouvelles");

        jPanel_header_toolbar.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jPanel_header_toolbarLayout = new javax.swing.GroupLayout(jPanel_header_toolbar);
        jPanel_header_toolbar.setLayout(jPanel_header_toolbarLayout);
        jPanel_header_toolbarLayout.setHorizontalGroup(
            jPanel_header_toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel_header_toolbarLayout.setVerticalGroup(
            jPanel_header_toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel_headerLayout = new javax.swing.GroupLayout(jPanel_header);
        jPanel_header.setLayout(jPanel_headerLayout);
        jPanel_headerLayout.setHorizontalGroup(
            jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_header_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel_header_toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_headerLayout.setVerticalGroup(
            jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_headerLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel_header_title, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_header_toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel_bottom.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_bottom.setPreferredSize(new java.awt.Dimension(800, 435));

        jPanel_export.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));

        jFileChooser_export.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        jFileChooser_export.setApproveButtonText("Sauvegarder");
        jFileChooser_export.setApproveButtonToolTipText("Save file");
        jFileChooser_export.setControlButtonsAreShown(true);
        jFileChooser_export.setDialogTitle("");
        jFileChooser_export.setToolTipText("");
        jFileChooser_export.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jFileChooser_export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser_exportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_exportLayout = new javax.swing.GroupLayout(jPanel_export);
        jPanel_export.setLayout(jPanel_exportLayout);
        jPanel_exportLayout.setHorizontalGroup(
            jPanel_exportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser_export, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );
        jPanel_exportLayout.setVerticalGroup(
            jPanel_exportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser_export, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel_bottomLayout = new javax.swing.GroupLayout(jPanel_bottom);
        jPanel_bottom.setLayout(jPanel_bottomLayout);
        jPanel_bottomLayout.setHorizontalGroup(
            jPanel_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_bottomLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel_export, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        jPanel_bottomLayout.setVerticalGroup(
            jPanel_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_bottomLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel_export, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_header, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_bottom, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel_bottom, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * La fenêtre pour sauvegarder le fichier XML
     * @param evt l'action produite
     */
    private void jFileChooser_exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser_exportActionPerformed
        //si on clique sur save, le fichier est créé, sinon on ferme la fenêtre
        if (evt.getActionCommand().equals(javax.swing.JFileChooser.APPROVE_SELECTION)) {
            eventsList.exportXML(jFileChooser_export.getCurrentDirectory() + "/" + jFileChooser_export.getSelectedFile().getName());
            this.dispose();
        } else if (evt.getActionCommand().equals(javax.swing.JFileChooser.CANCEL_SELECTION)) {
            this.dispose();
        }
    }//GEN-LAST:event_jFileChooser_exportActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser_export;
    private javax.swing.JLabel jLabel_header_title;
    private javax.swing.JPanel jPanel_bottom;
    private javax.swing.JPanel jPanel_export;
    private javax.swing.JPanel jPanel_header;
    private javax.swing.JPanel jPanel_header_toolbar;
    // End of variables declaration//GEN-END:variables
}
