/*
 * Ce programme permet d'importer un fil de nouvelles pour ensuite consulter ses nouvelles.
 * Il permet égallement d'exporter le fil de nouvelles dans un fichier XML et 
 * de créer, supprimer ou modifier ses nouvelles.
 */
package rss_projet4;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.Transferable;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.io.IOException;
import javax.swing.UIManager;

/**
 * Classe pour importer un fil de nouvelles à partir d'un hyperlien de type RSS ou d'un fichier
 * @author Sylvain
 */
public class Feeds_importJDialog extends javax.swing.JDialog {
     
    private final Controller eventsList; //accède au contrôleur
            
     /**
      * Constructeur de la vue d'importation
      * @param eventsList le fil de nouvelles
      */
    public Feeds_importJDialog(Controller eventsList) {
        this.eventsList = eventsList;
        
        //change le texte du bouton
        UIManager.put("FileChooser.cancelButtonText", "Annuler"); //change le texte du bouton

        initComponents();       
    } 
    
    /**
     * Accède au texte contenu dans le clipboard
     * @return le texte contenu dans le clipboard ou rien s'il est vide
     */
    private String paste() {
        String result = "";
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        Transferable contents = clipboard.getContents(null);
        boolean hasTransferableText = (contents != null) && contents.isDataFlavorSupported(DataFlavor.stringFlavor);
        if (hasTransferableText) {
            try {
                result = (String)contents.getTransferData(DataFlavor.stringFlavor);
            }
            catch (UnsupportedFlavorException | IOException fl){
            }            
        }
        return result;
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_header = new javax.swing.JPanel();
        jLabel_header_title = new javax.swing.JLabel();
        jPanel_header_toolbar = new javax.swing.JPanel();
        jPanel_bottom = new javax.swing.JPanel();
        jPanel_bottom_feeds_import = new javax.swing.JPanel();
        jTextField_feeds_import_url = new javax.swing.JTextField();
        jButton_feeds_import_url_coller = new javax.swing.JButton();
        jButton_import = new javax.swing.JButton();
        jButton_annuler = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel_import = new javax.swing.JPanel();
        jFileChooser_import = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        jPanel_header.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_header_title.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        jLabel_header_title.setForeground(new java.awt.Color(0, 153, 204));
        jLabel_header_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_header_title.setText("Importer un fil de nouvelles");

        jPanel_header_toolbar.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jPanel_header_toolbarLayout = new javax.swing.GroupLayout(jPanel_header_toolbar);
        jPanel_header_toolbar.setLayout(jPanel_header_toolbarLayout);
        jPanel_header_toolbarLayout.setHorizontalGroup(
            jPanel_header_toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel_header_toolbarLayout.setVerticalGroup(
            jPanel_header_toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel_headerLayout = new javax.swing.GroupLayout(jPanel_header);
        jPanel_header.setLayout(jPanel_headerLayout);
        jPanel_headerLayout.setHorizontalGroup(
            jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_header_title, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel_header_toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_headerLayout.setVerticalGroup(
            jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_headerLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel_header_title, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_header_toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel_bottom.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_bottom.setPreferredSize(new java.awt.Dimension(700, 460));

        jPanel_bottom_feeds_import.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_bottom_feeds_import.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2), "Hyperlien:"));

        jTextField_feeds_import_url.setPreferredSize(new java.awt.Dimension(730, 26));

        jButton_feeds_import_url_coller.setText("Coller ");
        jButton_feeds_import_url_coller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_feeds_import_url_collerActionPerformed(evt);
            }
        });

        jButton_import.setText("Importer");
        jButton_import.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_import.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_importActionPerformed(evt);
            }
        });

        jButton_annuler.setText("Annuler");
        jButton_annuler.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_annulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_bottom_feeds_importLayout = new javax.swing.GroupLayout(jPanel_bottom_feeds_import);
        jPanel_bottom_feeds_import.setLayout(jPanel_bottom_feeds_importLayout);
        jPanel_bottom_feeds_importLayout.setHorizontalGroup(
            jPanel_bottom_feeds_importLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_bottom_feeds_importLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel_bottom_feeds_importLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_bottom_feeds_importLayout.createSequentialGroup()
                        .addComponent(jButton_feeds_import_url_coller)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                        .addComponent(jButton_import)
                        .addGap(5, 5, 5)
                        .addComponent(jButton_annuler)
                        .addContainerGap(231, Short.MAX_VALUE))
                    .addGroup(jPanel_bottom_feeds_importLayout.createSequentialGroup()
                        .addComponent(jTextField_feeds_import_url, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(15, 15, 15))))
        );
        jPanel_bottom_feeds_importLayout.setVerticalGroup(
            jPanel_bottom_feeds_importLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_bottom_feeds_importLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jTextField_feeds_import_url, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_bottom_feeds_importLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_feeds_import_url_coller)
                    .addGroup(jPanel_bottom_feeds_importLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton_import)
                        .addComponent(jButton_annuler)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_bottomLayout = new javax.swing.GroupLayout(jPanel_bottom);
        jPanel_bottom.setLayout(jPanel_bottomLayout);
        jPanel_bottomLayout.setHorizontalGroup(
            jPanel_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_bottomLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel_bottom_feeds_import, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        jPanel_bottomLayout.setVerticalGroup(
            jPanel_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_bottomLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jPanel_bottom_feeds_import, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel_import.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_import.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2), "Fichier:"));

        jFileChooser_import.setApproveButtonText("Ouvrir");
        jFileChooser_import.setApproveButtonToolTipText("Open file");
        jFileChooser_import.setCurrentDirectory(new java.io.File("/Users/sylvain/Dropbox/Formation/Teluq/INF-1420/Projet4"));
        jFileChooser_import.setDialogTitle("");
        jFileChooser_import.setToolTipText("");
        jFileChooser_import.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jFileChooser_import.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser_importActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_importLayout = new javax.swing.GroupLayout(jPanel_import);
        jPanel_import.setLayout(jPanel_importLayout);
        jPanel_importLayout.setHorizontalGroup(
            jPanel_importLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser_import, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_importLayout.setVerticalGroup(
            jPanel_importLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_importLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jFileChooser_import, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel_import, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel_import, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_header, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_bottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel_bottom, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Bouton d'importation de l'hyperlien
     * @param evt l'action produite
     */
    private void jButton_importActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_importActionPerformed
        eventsList.importXML(jTextField_feeds_import_url.getText());
        this.dispose();
    }//GEN-LAST:event_jButton_importActionPerformed

    /**
     * Bouton d'annulation
     * @param evt l'action produite
     */
    private void jButton_annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_annulerActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_annulerActionPerformed

    /**
     * Bouton pour coller le texte contenu dans le clipboard (pour facilité le copier / coller)
     * @param evt l'action produite
     */
    private void jButton_feeds_import_url_collerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_feeds_import_url_collerActionPerformed
       jTextField_feeds_import_url.setText(paste());
    }//GEN-LAST:event_jButton_feeds_import_url_collerActionPerformed

    /**
     * La fenêtre pour ouvrir un fichier XML et l'importer
     * @param evt l'action produite
     */    
    private void jFileChooser_importActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser_importActionPerformed
        //si on clique sur ouvrir, le fichier est importé, sinon on ferme la fenêtre
        if (evt.getActionCommand().equals(javax.swing.JFileChooser.APPROVE_SELECTION)) {
            eventsList.importXML(jFileChooser_import.getSelectedFile().getName());
        this.dispose();
        } else if (evt.getActionCommand().equals(javax.swing.JFileChooser.CANCEL_SELECTION)) {
            this.dispose();
        }
    }//GEN-LAST:event_jFileChooser_importActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_annuler;
    private javax.swing.JButton jButton_feeds_import_url_coller;
    private javax.swing.JButton jButton_import;
    private javax.swing.JFileChooser jFileChooser_import;
    private javax.swing.JLabel jLabel_header_title;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_bottom;
    private javax.swing.JPanel jPanel_bottom_feeds_import;
    private javax.swing.JPanel jPanel_header;
    private javax.swing.JPanel jPanel_header_toolbar;
    private javax.swing.JPanel jPanel_import;
    private javax.swing.JTextField jTextField_feeds_import_url;
    // End of variables declaration//GEN-END:variables
}
